using System.Collections.Generic;
using SharpHook.Native;

namespace SoundBinder.Utils;

public static class StringUtils {
 
        public readonly static Dictionary<KeyCode, string> KeyCodeToStringMap = new()
    {
        // Undefined
        { KeyCode.VcUndefined, "Undefined" },
        
        // Normal keys
        { KeyCode.VcEscape, "Escape" },
        { KeyCode.VcF1, "F1" },
        { KeyCode.VcF2, "F2" },
        { KeyCode.VcF3, "F3" },
        { KeyCode.VcF4, "F4" },
        { KeyCode.VcF5, "F5" },
        { KeyCode.VcF6, "F6" },
        { KeyCode.VcF7, "F7" },
        { KeyCode.VcF8, "F8" },
        { KeyCode.VcF9, "F9" },
        { KeyCode.VcF10, "F10" },
        { KeyCode.VcF11, "F11" },
        { KeyCode.VcF12, "F12" },
        { KeyCode.VcF13, "F13" },
        { KeyCode.VcF14, "F14" },
        { KeyCode.VcF15, "F15" },
        { KeyCode.VcF16, "F16" },
        { KeyCode.VcF17, "F17" },
        { KeyCode.VcF18, "F18" },
        { KeyCode.VcF19, "F19" },
        { KeyCode.VcF20, "F20" },
        { KeyCode.VcF21, "F21" },
        { KeyCode.VcF22, "F22" },
        { KeyCode.VcF23, "F23" },
        { KeyCode.VcF24, "F24" },
        { KeyCode.VcBackQuote, "`" },
        { KeyCode.Vc1, "1" },
        { KeyCode.Vc2, "2" },
        { KeyCode.Vc3, "3" },
        { KeyCode.Vc4, "4" },
        { KeyCode.Vc5, "5" },
        { KeyCode.Vc6, "6" },
        { KeyCode.Vc7, "7" },
        { KeyCode.Vc8, "8" },
        { KeyCode.Vc9, "9" },
        { KeyCode.Vc0, "0" },
        { KeyCode.VcMinus, "-" },
        { KeyCode.VcEquals, "=" },
        { KeyCode.VcBackspace, "Backspace" },
        { KeyCode.VcTab, "Tab" },
        { KeyCode.VcCapsLock, "Caps Lock" },
        { KeyCode.VcA, "A" },
        { KeyCode.VcB, "B" },
        { KeyCode.VcC, "C" },
        { KeyCode.VcD, "D" },
        { KeyCode.VcE, "E" },
        { KeyCode.VcF, "F" },
        { KeyCode.VcG, "G" },
        { KeyCode.VcH, "H" },
        { KeyCode.VcI, "I" },
        { KeyCode.VcJ, "J" },
        { KeyCode.VcK, "K" },
        { KeyCode.VcL, "L" },
        { KeyCode.VcM, "M" },
        { KeyCode.VcN, "N" },
        { KeyCode.VcO, "O" },
        { KeyCode.VcP, "P" },
        { KeyCode.VcQ, "Q" },
        { KeyCode.VcR, "R" },
        { KeyCode.VcS, "S" },
        { KeyCode.VcT, "T" },
        { KeyCode.VcU, "U" },
        { KeyCode.VcV, "V" },
        { KeyCode.VcW, "W" },
        { KeyCode.VcX, "X" },
        { KeyCode.VcY, "Y" },
        { KeyCode.VcZ, "Z" },
        
        // Symbols
        { KeyCode.VcOpenBracket, "[" },
        { KeyCode.VcCloseBracket, "]" },
        { KeyCode.VcBackslash, "\\" },
        { KeyCode.VcSemicolon, ";" },
        { KeyCode.VcQuote, "'" },
        { KeyCode.VcEnter, "Enter" },
        { KeyCode.VcComma, "," },
        { KeyCode.VcPeriod, "." },
        { KeyCode.VcSlash, "/" },
        { KeyCode.VcSpace, "Space" },
        { KeyCode.VcUnderscore, "_" },
        
        // Weird Ones
        { KeyCode.Vc102, "<> or \\|" },
        { KeyCode.VcMisc, "Misc" },
        { KeyCode.VcPrintScreen, "Print Screen" },
        { KeyCode.VcScrollLock, "Scroll Lock" },
        { KeyCode.VcPause, "Pause" },
        { KeyCode.VcCancel, "Cancel" },
        { KeyCode.VcHelp, "Help" },
        
        { KeyCode.VcInsert, "Insert" },
        { KeyCode.VcDelete, "Delete" },
        { KeyCode.VcHome, "Home" },
        { KeyCode.VcEnd, "End" },
        { KeyCode.VcPageUp, "Page Up" },
        { KeyCode.VcPageDown, "Page Down" },
        
        // Arrow Keys
        { KeyCode.VcUp, "Up Arrow" },
        { KeyCode.VcLeft, "Left Arrow" },
        { KeyCode.VcRight, "Right Arrow" },
        { KeyCode.VcDown, "Down Arrow" },
        
        // Number Pad
        { KeyCode.VcNumLock, "Num Lock" },
        { KeyCode.VcNumPadClear, "Num-Pad Clear" },
        { KeyCode.VcNumPadDivide, "Num-Pad /" },
        { KeyCode.VcNumPadMultiply, "Num-Pad *" },
        { KeyCode.VcNumPadSubtract, "Num-Pad -" },
        { KeyCode.VcNumPadAdd, "Num-Pad +" },
        { KeyCode.VcNumPadEnter, "Num-Pad Enter" },
        { KeyCode.VcNumPadDecimal, "Num-Pad Decimal" },
        { KeyCode.VcNumPad0, "Num-Pad 0" },
        { KeyCode.VcNumPad1, "Num-Pad 1" },
        { KeyCode.VcNumPad2, "Num-Pad 2" },
        { KeyCode.VcNumPad3, "Num-Pad 3" },
        { KeyCode.VcNumPad4, "Num-Pad 4" },
        { KeyCode.VcNumPad5, "Num-Pad 5" },
        { KeyCode.VcNumPad6, "Num-Pad 6" },
        { KeyCode.VcNumPad7, "Num-Pad 7" },
        { KeyCode.VcNumPad8, "Num-Pad 8" },
        { KeyCode.VcNumPad9, "Num-Pad 9" },
        
        // Control Keys
        { KeyCode.VcLeftShift, "Left Shift" },
        { KeyCode.VcRightShift, "Right Shift" },
        { KeyCode.VcLeftControl, "Left Control" },
        { KeyCode.VcRightControl, "Right Control" },
        { KeyCode.VcLeftAlt, "Left Alt" },
        { KeyCode.VcRightAlt, "Right Alt" },
        { KeyCode.VcLeftMeta, "Left Meta" },
        { KeyCode.VcRightMeta, "Right Meta" },
        { KeyCode.VcContextMenu, "Context Menu" },
        { KeyCode.VcFunction, "Function" },
        
        { KeyCode.VcChangeInputSource, "Change Input Source" },
        { KeyCode.VcPower, "Power" },
        { KeyCode.VcSleep, "Sleep" },
        
        // Media Controls
        { KeyCode.VcMediaPlay, "Play/Pause Media" },
        { KeyCode.VcMediaStop, "Stop Media" },
        { KeyCode.VcMediaPrevious, "Previous Media" },
        { KeyCode.VcMediaNext, "Next Media" },
        { KeyCode.VcMediaSelect, "Select Media" },
        { KeyCode.VcMediaEject, "Eject Media" },

        // Volume Controls
        { KeyCode.VcVolumeMute, "Volume Mute" },
        { KeyCode.VcVolumeDown, "Volume Down" },
        { KeyCode.VcVolumeUp, "Volume Up" },
        
        // App Shortcuts
        { KeyCode.VcApp1, "Launch App 1" },
        { KeyCode.VcApp2, "Launch App 2" },
        { KeyCode.VcApp3, "Launch App 3" },
        { KeyCode.VcApp4, "Launch App 4" },
        { KeyCode.VcAppBrowser, "Launch Browser" },
        { KeyCode.VcAppCalculator, "Launch Calculator" },
        { KeyCode.VcAppMail, "Launch Mail" },
        
        // Browser Control
        { KeyCode.VcBrowserSearch, "Browser Search" },
        { KeyCode.VcBrowserHome, "Browser Home" },
        { KeyCode.VcBrowserBack, "Browser Back" },
        { KeyCode.VcBrowserForward, "Browser Forward" },
        { KeyCode.VcBrowserStop, "Browser Stop" },
        { KeyCode.VcBrowserRefresh, "Browser Refresh" },
        { KeyCode.VcBrowserFavorites, "Browser Favorites" },
        
        // Language Toggles
        { KeyCode.VcKatakanaHiragana, "KatakanaHiragana" },
        { KeyCode.VcKatakana, "Katakana" },
        { KeyCode.VcHiragana, "Hiragana" },
        { KeyCode.VcKana, "Kana" },
        { KeyCode.VcKanji, "Kanji" },
        { KeyCode.VcHangul, "Hangul" },
        { KeyCode.VcJunja, "Junja" },
        { KeyCode.VcFinal, "Final" },
        { KeyCode.VcHanja, "Hanja" },
        { KeyCode.VcAccept, "Accept" },
        { KeyCode.VcConvert, "Convert" },
        { KeyCode.VcNonConvert, "NonConvert" },
        { KeyCode.VcImeOn, "IME On" },
        { KeyCode.VcImeOff, "IME Off" },
        { KeyCode.VcModeChange, "Mode Change" },
        { KeyCode.VcProcess, "Process" },
    };
        
    public static string GetKeyCodeString(KeyCode code) => KeyCodeToStringMap[code];
}